### ISSUE TITLE
Error Updating System via Manifest-Link

### ISSUE THREAD

**Issue by tagnullde** [ThirteenStrings/crown-and-skull#1]
I am pleased to see a System for Crown and Skull. Just bought the book. So thank you.
Anyway - the system isn't yet listed in the system browser in foundry. So I decided to install it for a testdrive via the manifest link.
Hitting update all systems yielded an error message:

![image](https://github.com/user-attachments/assets/53ff8fcb-a36f-42da-9380-f0c977a506ba)

Nothing major, but I thought I will let you know.

**Comment by ThirteenStrings** [comment]
Error should be fixed now. Thank you for posting this!
